# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-15 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoPedido', models.CharField(max_length=50)),
                ('domicilioPedido', models.CharField(max_length=50)),
                ('fechaPedido', models.DateField()),
                ('valorPedido', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcionProducto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precioProducto',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='pedido',
            field=models.ManyToManyField(to='producto.Pedido'),
        ),
    ]
